modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="secretgif"
version="1.0.0"
displayName="SecretGIF"
description="Показывай GIF-ки над головой всем игрокам!"

[[dependencies.secretgif]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.secretgif]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH